=== pboopathi-jama/RestApiValidation/OpenWeatherMapGetWeather_outputSchema.json
{ "type": "object", "additionalProperties": false,"properties": { "coord": { "type": "object", "additionalProperties": false,"properties": { "lon": { "type": "number", "minimum": -9223372036854776000, "maximum": 9223372036854776000 }, "lat": { "type": "number", "minimum": -9223372036854776000, "maximum": 9223372036854776000 } } }, "weather": { "type": "array", "items": { "type": "object", "additionalProperties": false,"properties": { "id": { "type": "number", "minimum": -9223372036854776000, "maximum": 9223372036854776000 }, "main": { "type": "string" }, "description": { "type": "string" }, "icon": { "type": "string" } } } }, "base": { "type": "string" }, "main": { "type": "object", "additionalProperties": false,"properties": { "temp": { "type": "number" }, "pressure": { "type": "number" }, "humidity": { "type": "number" }, "temp_min": { "type": "number" }, "temp_max": { "type": "number" }, "grnd_level": { "type": "number" }, "sea_level": { "type": "number" } } }, "visibility": { "type": "number" }, "wind": { "type": "object", "additionalProperties": false,"properties": { "speed": { "type": "number" }, "deg": { "type": "number" }, "gust": { "type": "number" } } }, "clouds": { "type": "object", "additionalProperties": false,"properties": { "all": { "type": "number" } } }, "dt": { "type": "number" }, "sys": { "type": "object", "additionalProperties": false,"properties": { "type": { "type": "number" }, "id": { "type": "number" }, "message": { "type": "number" }, "country": { "type": "string" }, "sunset": { "type": "number" }, "sunrise": { "type": "number" } } }, "rain": { "type": "object", "additionalProperties": false,"properties": { "1h": { "type": "number" } } }, "id": { "type": "number" }, "name": { "type": "string" }, "cod": { "type": "number" }, "timezone": { "type": "number" }, "snow": { "type": "object", "additionalProperties": false,"properties": { "1h": { "type": "number" } } } }, "$schema": "http://json-schema.org/draft-04/schema#" }

=== pboopathi-jama/RestApiValidation/OpenWeatherMapGetWeather_responseFromApi.json
{
  "coord" : {
    "lon" : -105.41,
    "lat" : 36.71
  },
  "weather" : [ {
    "id" : 804,
    "main" : "Clouds",
    "description" : "overcast clouds",
    "icon" : "04d"
  } ],
  "base" : "stations",
  "main" : {
    "temp" : 285.5,
    "pressure" : 1012,
    "humidity" : 39,
    "temp_min" : 280.93,
    "temp_max" : 288.71
  },
  "visibility" : 16093,
  "wind" : {
    "speed" : 5.7,
    "deg" : 230,
    "gust" : 10.3
  },
  "clouds" : {
    "all" : 85
  },
  "dt" : 1558554843,
  "sys" : {
    "type" : 1,
    "id" : 3371,
    "message" : 0.0058,
    "country" : "US",
    "sunrise" : 1558525769,
    "sunset" : 1558577245
  },
  "id" : 5485658,
  "name" : "Red River",
  "cod" : 200,
  "timezone" : -21600
}
